name: DAST Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://85.193.90.138:8080 \
            -r /zap/wrk/report_html.html \
            -w /zap/wrk/report.md \
            -J /zap/wrk/report.json
            
      - name: Prepare reports
        run: |
          mkdir -p reports
          mv report_html.html reports/index.html
          mv report_json.json reports/report.json

      - name: Upload ZAP report artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    needs: zap_scan
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
