name: DAST Scan

on:
  push:
    branches: [ "master" ]

jobs:
  zap-scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t ${{ secrets.TARGET_URL }} \
            -J report_json.json \
            -r report_html.html || true

      - name: Move reports into folder
        run: |
          mkdir -p reports
          mv report_html.html reports/
          mv report_json.json reports/

      - name: Upload ZAP report artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./reports

  deploy:
    name: Deploy ZAP Report
    runs-on: ubuntu-latest
    needs: zap-scan
    permissions:
      pages: write      # нужно для деплоя
      id-token: write   # тоже нужно для деплоя
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
