name: DAST Scan

on:
  push:
    branches: ["master", "main"]

jobs:
  zap-scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t ${{ secrets.TARGET_URL }} \
            -r report_html.html \
            -J report_json.json

      - name: Move reports into folder
        run: |
          mkdir -p reports
          mv report_html.html reports/index.html
          mv report_json.json reports/

      - name: Upload ZAP report artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    needs: zap-scan
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ZAP Report
        id: deployment
        uses: actions/deploy-pages@v4
