name: Deploy reports

on:
  workflow_run:
    workflows: ["DAST", "Security Checks", "SAST"]   # твои workflow
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
